export{ default as Navbar } from './Navbar'
export{ default as Hero } from './Hero'
export{ default as WhyUs } from './WhyUs'
export{ default as Menu } from './Menu'
export{ default as Footer } from './Footer'